//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kakarot {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("kakarot.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parchear ROM (IPS).
        /// </summary>
        internal static string AplicarParche {
            get {
                return ResourceManager.GetString("AplicarParche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        internal static string Buscar {
            get {
                return ResourceManager.GetString("Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Concatenar.
        /// </summary>
        internal static string Concatenar {
            get {
                return ResourceManager.GetString("Concatenar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Convertir a.
        /// </summary>
        internal static string Convertir_a {
            get {
                return ResourceManager.GetString("Convertir a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descargar seleccion.
        /// </summary>
        internal static string Descargar_seleccion {
            get {
                return ResourceManager.GetString("Descargar seleccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descomprimir despues de descargar.
        /// </summary>
        internal static string DescomprimirDespuesDeDescargar {
            get {
                return ResourceManager.GetString("DescomprimirDespuesDeDescargar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ejecuta ROM/DSK/CAS/WAV.
        /// </summary>
        internal static string EjecutaROM_DSK_CAS_WAV {
            get {
                return ResourceManager.GetString("EjecutaROM/DSK/CAS/WAV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ejecuta Seleccionado.
        /// </summary>
        internal static string EjecutaSeleccionado {
            get {
                return ResourceManager.GetString("EjecutaSeleccionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Establecer ruta para OpenMSX.
        /// </summary>
        internal static string EstablecerRutaParaOpenMSX {
            get {
                return ResourceManager.GetString("EstablecerRutaParaOpenMSX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtro rápido.
        /// </summary>
        internal static string FiltroRapido {
            get {
                return ResourceManager.GetString("FiltroRapido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Herramientas.
        /// </summary>
        internal static string Herramientas {
            get {
                return ResourceManager.GetString("Herramientas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        internal static string Idioma {
            get {
                return ResourceManager.GetString("Idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Informar de actualizaciones.
        /// </summary>
        internal static string InformarDeActualizaciones {
            get {
                return ResourceManager.GetString("InformarDeActualizaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opciones.
        /// </summary>
        internal static string Opciones {
            get {
                return ResourceManager.GetString("Opciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permitir multiples instancias.
        /// </summary>
        internal static string PermitirMultiplesInstancias {
            get {
                return ResourceManager.GetString("PermitirMultiplesInstancias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Respositorios.
        /// </summary>
        internal static string Repos {
            get {
                return ResourceManager.GetString("Repos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver novedades.
        /// </summary>
        internal static string VerNovedades {
            get {
                return ResourceManager.GetString("VerNovedades", resourceCulture);
            }
        }
    }
}
